version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    container_name: fintech-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fintech
    ports:
      - "5432:5432"

  api:
    container_name: fintech-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:postgres@localhost:5432/fintech?sslmode=disable
    depends_on:
      - postgres
